/*
Each new term in the Fibonacci sequence is
generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
#include <iostream> 

using namespace std;

int main(int argc, char** argv){

int check = 4000000, test=100, temp1 =0, temp2 =1, placeholder=0,  sum=0;

while(sum < check){
	cout << temp1 << " + " <<temp2 << " \n";
	placeholder = temp2;
	temp2 = temp1+temp2;
	temp1 = placeholder;
	if ((temp2%2)==0){ 
		cout << "this fib number is even, I am adding " << temp2 << endl;
		sum = sum+temp2;
	}
}
cout << "all the even prime summed is " << sum << endl; 
cout << "\nthe sum is " << sum<< endl;;


}